name: CI/CD for Dockerized App

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Log in to DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Build and push Docker image
    - name: Build and push Docker image
      run: |
        docker build -t ramatjyotsingh/umatt-website .
        docker push  ramatjyotsingh/umatt-website

    # Step 4: SSH into EC2 and deploy
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          docker pull ramatjyotsingh/umatt-website
          docker stop website || true
          docker rm website || true
          docker run -d --name website -p 80:80 ramatjyotsingh/umatt-website
